### ISSUE TITLE
What is the situation of the Privacy Sandbox on Android?

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-android#52]
@n-aggarwal brought up this good point.

- Is it already implemented?
- Can people opt out?
- How does it work?

Here is a [starting point](https://developer.android.com/design-for-safety/privacy-sandbox/topics).

**Comment by n-aggarwal** [comment]
“Privacy Sandbox will introduce new technology that operates without cross-app identifiers – including Advertising ID. This helps apps remain free through ads while your data stays protected.” [Privacy Sandbox](https://privacysandbox.com/android/#proposals-for-android)

Here is the GitHub for Privacy Sandbox: https://github.com/privacysandbox ; might be a good idea to keep an eye on it. 

Here is an overview of [Topics API and its implementation](https://developer.android.com/design-for-safety/privacy-sandbox/topics). The big idea here is that the API intends to provide callers with coarse-grained advertising topics of interest based on the user's app usage, which can then be used by the apps to show relevant ads. 

Here is an overview of [Fledge API and its implementation](https://developer.android.com/design-for-safety/privacy-sandbox/fledge). The big idea here is custom audience targeting. The Audience information is stored on-device and can be associated with relevant candidate ads for the audience and arbitrary metadata, such as bidding signals.

At the bottom of both the Topics and Fledge API pages, the user side control overview is given. It seems that they are going to make it harder, reduce usability as users would have to go into Topics API and Fledge API settings separately and then disable them. I am not sure even if there will be a “clear all interests” or a similar button; from what I am reading it might be a tedious one by one deletion process.

There seem to be two early release programs— [beta (for user side testing) and Developer program (for developer side testing)](https://developer.android.com/design-for-safety/privacy-sandbox/program-overview?version=preview#dp-program). Both the beta and developer program require the client to [sign up](https://developer.android.com/design-for-safety/privacy-sandbox/enroll) in order to participate. It might be beneficial to enroll into these programs to see the upcoming changes.

Google also seems to have started [beta testing for Privacy Sandbox on the user side](https://blog.google/products/android/the-privacy-sandbox-beta-is-coming-to-android/) for a small number of phones with android 13.  As of right now, there doesn't seem to be any Privacy Sandbox for android 14 which is being released in August this year.
